### ISSUE TITLE
Put `.mod` files on `.gitignore`

### ISSUE THREAD

**Issue by minhqdao** [fortran-lang/fpm#758]
When working with the [Modern Fortran](https://github.com/fortran-lang/vscode-fortran-support) plugin in VSCode, `.mod` files are continuously generated and I think it makes sense to exclude them from VC by adding them to `.gitignore`.

The `.mod` files in the example folders should also be excluded.

I think it also makes sense to also add them to the template for generating fpm packages.

**Comment by awvwgk** [comment]
`.mod` files should never be generated in source tree, this issue should be addressed in Modern Fortran to store the `.mod` files in a dedicated directory like done by other tools, *e.g.* fpm is using `build/`.

**Comment by awvwgk** [comment]
I recall that LFortran was not honoring the `-J` option passed by fpm when I first implemented support it and instead stored the `.mod` files in the current working directory. If you are using LFortran as linter in Modern Fortran this might be an LFortran issue rather than an Modern Fortran / VSCode issue.

**Comment by LKedward** [comment]
Thanks @minhqdao. As Sebastian has said, this is an issue with the vscode Modern Fortran plugin not with fpm. As a solution, I would recommend explicitly specifying a module directory to the Modern Fortran plugin:

```
{
  "fortran.linter.extraArgs" : [
    "-Jbuild" 
  ] 
} 
```

Alternatively, you could suggest a PR to the Modern Fortran plugin to make this the default for fpm projects.

**Comment by minhqdao** [comment]
> Thanks @minhqdao. As Sebastian has said, this is an issue with the vscode Modern Fortran plugin not with fpm. As a solution, I would recommend explicitly specifying a module directory to the Modern Fortran plugin:
> 
> ```
> {
>   "fortran.linter.extraArgs" : [
>     "-Jbuild" 
>   ] 
> } 
> ```
> 
> Alternatively, you could suggest a PR to the Modern Fortran plugin to make this the default for fpm projects.

Thanks for the suggestion, @LKedward, but it seems that `lfortran` isn't able to find the `build` folder to write the `.mod` files in with the `-Jbuild` argument. I'll raise an issue there and put the `.mod` files in my global `.gitignore` while this isn't resolved.

**Comment by minhqdao** [comment]
Man, I don't know why I thought it was `lfortran`, but the compiler I'm using for linting is actually `gfortran`. Nevertheless, using the argument `-J${workspaceFolder}/build` puts `.mod` files in the `build` folder. But it only works if the `build` folder already exists.

`-J${workspaceFolder}/build/mod` makes it even cleaner, but one definitely has to manually create that folder.
